using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sollang.Compiler.Generators;

// Semantic annotations use syntax identity. Derive deep copies from the record
// model so new syntax forms cannot accidentally share generic call sites.
[Generator(LanguageNames.CSharp)]
public sealed class SyntaxCloneGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            var expression = compilation.GetTypeByMetadataName("Sollang.Compiler.Syntax.Expression");
            if (expression is null) return;
            var records = expression.ContainingNamespace.GetTypeMembers()
                .Where(static type => type.IsRecord && !type.IsValueType)
                .OrderBy(static type => type.Name, System.StringComparer.Ordinal).ToArray();
            var source = new StringBuilder("// <auto-generated/>\n#nullable enable\nusing System.Linq;\nnamespace Sollang.Compiler.Syntax;\ninternal static class SyntaxCloner\n{\n");
            foreach (var record in records)
            {
                source.Append("    internal static ").Append(record.Name).Append("? Clone(")
                    .Append(record.Name).Append("? node)\n    {\n        if (node is null) return null;\n");
                if (record.IsAbstract)
                {
                    source.Append("        return node switch\n        {\n");
                    foreach (var child in records.Where(type => !type.IsAbstract && DerivesFrom(type, record)))
                        source.Append("            ").Append(child.Name).Append(" value => Clone(value)!,\n");
                    source.Append("            _ => throw new System.InvalidOperationException(\"Unknown syntax record\")\n        };\n");
                }
                else
                {
                    source.Append("        return node with\n        {\n");
                    foreach (var property in record.GetMembers().OfType<IPropertySymbol>()
                                 .Where(static property => property.SetMethod?.IsInitOnly == true))
                    {
                        var replacement = CloneValue(property.Type, "node." + property.Name);
                        if (replacement is not null)
                            source.Append("            ").Append(property.Name).Append(" = ").Append(replacement).Append(",\n");
                    }
                    source.Append("        };\n");
                }
                source.Append("    }\n");
            }
            source.Append("}\n");
            output.AddSource("SyntaxCloner.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    private static bool DerivesFrom(INamedTypeSymbol type, INamedTypeSymbol ancestor)
    {
        for (var current = type.BaseType; current is not null; current = current.BaseType)
            if (SymbolEqualityComparer.Default.Equals(current, ancestor)) return true;
        return false;
    }

    private static string? CloneValue(ITypeSymbol type, string value)
    {
        if (type is not INamedTypeSymbol named) return null;
        if (named.IsRecord && !named.IsValueType
            && named.ContainingNamespace.ToDisplayString() == "Sollang.Compiler.Syntax")
            return "Clone(" + value + ")" + (type.NullableAnnotation == NullableAnnotation.Annotated ? "" : "!");
        if (named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IReadOnlyList<T>")
        {
            var item = CloneValue(named.TypeArguments[0], "item");
            if (item is not null)
                return value + (type.NullableAnnotation == NullableAnnotation.Annotated ? "?" : "")
                    + ".Select(item => " + item + ").ToArray()";
        }
        return null;
    }
}
